---
# reliabot: mapping=4 offset=2 sequence=4
version: 2
updates:
  - package-ecosystem: npm
    directory: /   # Location of package manifests
    schedule:
        interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
        interval: daily
