name: 'Assign Labels From Conventional Commits'
description: 'Assign labels to pull-request parsing conventional commits standard'
author: Mauro Alderete
inputs:
  github-token:
    description: 'The Github token.'
    required: true
  conventional-commits:
    description: 'String with the YAML object or path to file YAML that contains a list with conventional commits and the labels matching that must be assigned'
    required: true
  pull-request-number:
    description: 'The pull request''s number where labels will be assigned'
    required: false
    default: '0'
  maintain-labels-not-matched:
    description: 'You should keep the conventional commit tags assigned to the pull-request, even though they are no longer referenced within commits.'
    required: false
    default: 'false'
  apply-changes:
    description: 'Should will be executing the action and save any change to the repository.'
    required: false
    default: 'true'
outputs:
  labels-previous:
    description: 'List of the labels assigned before the updating'
  labels-assigned:
    description: 'List of the labels added'
  labels-removed:
    description: 'List of the labels removed'
  labels-next:
    description: 'List of the labels assigned after the updating'
  action-status:
    description: 'Execution status of the action'
  action-message:
    description: 'Message associated to the current status of the action'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-square'
  color: 'orange'
